version: "3.9"
    
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_wordpress
    networks:
      - wordpress-overlay
    deploy:
      placement:
        constraints:
          - "node.labels.db==true"
      replicas: 1
    secrets:
      - db_wordpress
      - db_root
    
  frontend:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-overlay
    deploy:
      replicas: 3
    secrets: 
     - db_wordpress

secrets:
  db_root:
    file: db_root.txt
  db-wordpress:
    file: db_wordpress.txt

volumes:
  db_data:
  wordpress_data:
    driver_opts:
      type: "nfs"
      o: "addr=172.89.0.20,rw,nolock"
      device: ":/srv/wordpress"

networks:
  wordpress-overlay:
    driver: overlay
    attachable: true
    name: wordpress-overlay